name: Azure Pipelines

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
trigger:
  branches:
    include:
    - main
  paths:
    exclude:
    - README.md
    - .gitignore
    - images/*

# ToDo: Replace the agent pool name, if you are using Udacity Cloud lab. 
# Otherwise, comment out the line below. 
pool: MyAgentPool

variables:
  python.version: '3.7.6'
  # ToDo: Replace the service connection name as used in the DevOps project settings
  azureServiceConnectionId: '5389dd33-fc42-4780-9c6d-6b596e2a9dae'
  # Project root folder. Point to the folder containing manage.py file.
  projectRoot: $(System.DefaultWorkingDirectory)
  # Environment name
  environmentName: 'DEV'
  subscription : ''
  applicationname : 'webapp-anhdv29'
  backendServiceArm : 'AzureServiceConnection'
  sshKey: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCkNwjzVWi9K0w6LR/dRkIFdldWeROnDlauEj0OfV4YOKSuyMWjdz39VAZRSyIEyGgz2LeIGxX1rNyLbH/1zRQ358vVAEf6xEDTlImBiLr7R64FZmgrSWeauZKW2hhWdRSfJXD9uFKPdJuhdd+SJvIFY76tJe46Foc8jWRvgCQ10MhYwnFaopui+2XHHDtILoP6PDVQkn+P8zvA/le/Uw+/SUHfBVslifijhv4hKP03emqea6Se8dDdD/O6SwRqRYnUVkafa+1nJEaOjAwIQ6xOLc3K7TQA+sZ/oJHtdlGTVnmJKvqx90Be+3haCX1X7BhezrDMcIDlHgwn0NNOqAU7 dovietanh74@gmail.com'

stages:
#--------------------------------------------#  
# BUILD STAGE
#--------------------------------------------#    
- stage: Build_Infrastructure
  jobs:
  - job: BuildInfrastructure
    steps:
    - task: TerraformInstaller@0
      displayName: 'Terrafom installation'
      inputs:
        terraformVersion: '1.9.2'
    
    - task: TerraformCLI@1
      displayName: 'Terrafom init'
      inputs: 
        command: 'init'
        # commandOptions: 
        #   -reconfigure
        workingDirectory: '$(System.DefaultWorkingDirectory)/terraform/environments/test'
        backendServiceArm: '$(azureServiceConnectionId)'
        backendAzureRmResourceGroupName: 'Azuredevops'
        backendAzureRmStorageAccountName: 'tfstateanhdv29'
        backendAzureRmContainerName: 'tfstate'
        backendAzureRmKey: 'terraform.tfstate'

    - task: DownloadSecureFile@1
      name: tfvardef
      displayName: Download terraform.tfvars
      inputs:
        secureFile: 'terraform.tfvars'  
    - task: TerraformCLI@1
      displayName: Terraform validate
      inputs:
        command: 'validate'
    - task: InstallSSHKey@0
      inputs:
        #TODO 
        knownHostsEntry: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCj7ndNxQowgcQnjshcLrqPEiiphnt+VTTvDP6mHBL9j1aNUkY4Ue1gvwnGLVlOhGeYrnZaMgRK6+PKCUXaDbC7qtbW8gIkhL7aGCsOr/C56SJMy/BCZfxd1nWzAOxSDPgVsmerOBYfNqltV9/hWCqBywINIR+5dIg6JTJ72pcEpEjcYgXkE2YEFXV1JHnsKgbLWNlhScqb2UmyRkQyytRLtL+38TGxkxCflmO+5Z8CSSNY7GidjMIZ7Q4zMjA2n1nGrlTDkzwDCsw+wqFPGQA179cnfGWOWRVruj16z6XyvxvjJwbz0wQZ75XK5tKSb7FNyeIEs4TT4jk+S4dhPeAUC5y+bDYirYgM4GC7uEnztnZyaVWQ7B381AK4Qdrwt51ZqExKbQpTUNn+EjqoTwvqNj4kqx5QUCI0ThS/YkOxJCXmPUWZbhjpCg56i+2aB6CmK2JGhn57K5mj0MNdBXA4/WnwH6XoPWJzK5Nyu2zB3nAZp+S5hpQs+p1vN1/wsjk=' # variable value
        sshPublicKey: $(sshKey)
        sshKeySecureFile: 'id_rsa' # Use secure file feature in the pipeline library UI to save the "id_rsa" file, as mentioned here: https://learn.microsoft.com/en-us/azure/devops/pipelines/library/secure-files?view=azure-devops

    - task: Bash@3
      displayName: Copy terraform.tfvars
      inputs:
        targetType: 'inline'
        script: cp $(Agent.TempDirectory)/terraform.tfvars $(System.DefaultWorkingDirectory)/terraform/environments/test
    # - task: Bash@3
    #   displayName: fix terraform apply
    #   inputs:
    #     targetType: 'inline'
    #     script: terraform state push errored.tfstate
    #     workingDirectory: $(System.DefaultWorkingDirectory)/terraform/environments/test
    # - task: TerraformCLI@1
    #   displayName: Terraform Destroy
    #   inputs:
    #     command: 'destroy'
    #     commandOptions:
    #       -auto-approve
    #       -lock=false
    #     workingDirectory: '$(System.DefaultWorkingDirectory)/terraform/environments/test'
    - task: TerraformCLI@1
      displayName: Terraform apply
      inputs:
        command: 'apply'
        commandOptions: 
          -lock=false
        workingDirectory: '$(System.DefaultWorkingDirectory)/terraform/environments/test'
      retryCountOnTaskFailure: 3
      condition: succeededOrFailed()
    - script: |
        terraform state push errored.tfstate
      condition: failed()

# Build fake app
- stage: BuildFakeRestAPI
  jobs:
  - job: 'BuildFakeapp'
    displayName: 'Build Fake app Rest API'
    pool:
      name: MyAgentPool
    steps:
    - task: ArchiveFiles@2
      displayName: 'Archive FakeRestAPI'
      inputs:
        rootFolderOrFile: '$(System.DefaultWorkingDirectory)/automatedtesting/jmeter/fakerestapi'
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId)-fakerestapi.zip'
    - publish: $(Build.ArtifactStagingDirectory)/$(Build.BuildId)-fakerestapi.zip
      displayName: 'Upload Package'
      artifact: fakerestapi
# Deploy fake app

- stage: DeployFakeApp
  dependsOn: BuildFakeRestAPI
  condition: succeeded()
  jobs:
  - deployment: FakeRestAPI
    pool:
      # vmImage: 'Ubuntu-18.04'
      name: MyAgentPool
    environment: 'DEV'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureWebApp@1
            displayName: 'Deploy Azure Web App'
            inputs:
              azureSubscription: $(azureServiceConnectionId)
              appName: $(applicationname)
              appType: webApp
              package: $(Pipeline.Workspace)/fakerestapi/$(Build.BuildId)-fakerestapi.zip

# Build Test
- stage: Build_Test
  jobs:
  - job: Build
    pool:
      # vmImage: 'ubuntu-18.04'
      name: 'MyAgentPool'
    # steps:
    # - task: ArchiveFiles@2
    #   displayName: "Archive Selenium UI Tests"
    #   inputs:
    #     rootFolderOrFile: "$(System.DefaultWorkingDirectory)/automatedtesting/selenium"
    #     includeRootFolder: false
    #     archiveType: "zip"
    #     archiveFile: '$(Build.BuildId)/selenium-tests.zip'
    #     replaceExistingArchive: true
    # - upload: $(Build.BuildId)/selenium-tests.zip
    #   artifact: selenium
  - job: publishSelenium
    displayName: 'Publish Selenium'
    steps:
    - publish: $(System.DefaultWorkingDirectory)/automatedtesting/selenium/login.py
      artifact: selenium

    # - task: ArchiveFiles@2
    #   displayName: 'Archive Postman tests'
    #   inputs:
    #     rootFolderOrFile: '$(System.DefaultWorkingDirectory)/automatedtesting/postman'
    #     includeRootFolder: false
    #     archiveType: 'zip'
    #     archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId)-postman-tests.zip'
    # - publish: $(Build.ArtifactStagingDirectory)/$(Build.BuildId)-postman-tests.zip
    #   displayName: 'Upload Postman Tests'
    #   artifact: postman

    - task: ArchiveFiles@2
      displayName: 'Archive Jmeter tests'
      inputs:
        rootFolderOrFile: '$(System.DefaultWorkingDirectory)/automatedtesting/jmeter'
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId)-jmeter-tests.zip'
    - publish: $(Build.ArtifactStagingDirectory)/$(Build.BuildId)-jmeter-tests.zip
      displayName: 'Upload JMeter Tests'
      artifact: jmeter

# run test
- stage: RunTests     
  jobs:
  - deployment: UITests
    displayName: 'UI Tests'
    pool:
      # vmImage: 'ubuntu-18.04'
      name: MyAgentPool
    environment:  'DEV'
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            displayName: Download selenium
            artifact: selenium
          ####################################################################
          #                       Selenium Test                              #
          ####################################################################
          - task: Bash@3
            displayName: 'Install Selenium'
            inputs:
              targetType: 'inline'
              script: |
                sudo apt-get update -y
                sudo apt-get install python3-pip -y
                sudo apt-get install unzip -y
                sudo apt-get install -y chromium-browser
                sudo apt-get install -y chromium-chromedriver
                pip3 install selenium==4.7.2
                sudo mkdir -p /var/log/selenium
                sudo chmod 777 /var/log/selenium
                sudo python3 $(Pipeline.Workspace)/selenium/login.py 2>&1 | tee -a /var/log/selenium/selenium.log
                sudo touch /var/log/selenium/selenium.log
                
                # # download chrome driver v89
                # FILE=chromedriver_linux64.zip
                # if [ -f "$FILE" ]; then
                #   echo "$FILE exists."
                # else
                #   wget https://chromedriver.storage.googleapis.com/89.0.4389.23/chromedriver_linux64.zip
                # fi
                # # install chrome driver
                # unzip chromedriver_linux64.zip
                # sudo mv chromedriver /usr/bin/chromedriver
                # sudo chown root:root /usr/bin/chromedriver
                # sudo chmod +x /usr/bin/chromedriver
                # chromium-browser -version
                # chromedriver --version
                # # agent log analytics
                # wget https://raw.githubusercontent.com/Microsoft/OMS-Agent-for-Linux/master/installer/scripts/onboard_agent.sh && sh onboard_agent.sh -w ba2f2875-7939-40f7-8fab-9fdfe5774935 -s rb9iiVdW/SUHbVCH4V83NX16EgaXKTEtX7WfGSxykJ3iCaZ/Tm/FFqigsvOAUajQZM0L5k9vAnyM3lD4Iv61cw==
                # sudo /opt/microsoft/omsagent/bin/service_control restart ba2f2875-7939-40f7-8fab-9fdfe5774935
          
          # - download: current
          #   displayName: 'Download Selenium'
          # #   artifact: selenium
          # - task: Bash@3
          #   displayName: UI Tests
          #   inputs:
          #     targetType: 'inline'
          #     script: |
          #       unzip -o $(Pipeline.Workspace)/selenium/selenium-tests.zip -d .
          #       sudo mkdir /var/logs
          #       python3 login.py > ui-logs.log
          #       sudo mv ui-logs.log /var/logs
                 
           
          ###################################################################
          #                     JMeter   Test                              #
          ###################################################################
          - download: current
            displayName: Download JMeter
            artifact: jmeter
          - task: Bash@3
            displayName: Install JMeter and Run Test
            inputs:
              targetType: 'inline'
              script: |
                sudo apt-get update
                sudo apt install curl -y
                sudo apt-get -y install zip
                sudo apt install -y default-jre
                sudo apt install -y default-jdk
                sudo apt-get -y install zip

                wget "https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-5.6.2.tgz"
                tar -xf apache-jmeter-5.6.2.tgz
                unzip -o $(Build.BuildId)-jmeter-tests -d .
                ./apache-jmeter-5.6.2/bin/jmeter -n -t StressTestSuite.jmx \
                                          -l log/jmeter/stress-test-result.csv \
                                          -e -f -o log/jmeter/stress-test-html-report \
                                          -j log/jmeter/jmeter-stress-test.log
                ./apache-jmeter-5.6.2/bin/jmeter -n -t EnduranceTestSuite.jmx \
                                          -l log/jmeter/endurance-test-result.csv \
                                          -e -f -o log/jmeter/endurance-test-html-report \
                                          -j log/jmeter/jmeter-endurance-test.log
              workingDirectory:  $(Pipeline.Workspace)/jmeter
          - task: ArchiveFiles@2
            displayName: Archive JMeter test HTML report
            inputs:
              rootFolderOrFile: '$(Pipeline.Workspace)/jmeter/log/jmeter'
              includeRootFolder: false
              archiveType: 'zip'
              archiveFile: '$(Pipeline.Workspace)/jmeter/log/jmeter-$(Build.BuildId).zip'
              verbose: true

          - task: PublishPipelineArtifact@1
            displayName: Publish JMeter logs
            inputs:
              targetPath: '$(Pipeline.Workspace)/jmeter/log/jmeter-$(Build.BuildId).zip'
              artifactName: 'drop-jmeter-logs'
  - job: PostmanTests
    displayName: Postman Tests
    steps: 
    - task: NodeTool@0
      inputs:
        versionSpec: '16.x' 
        checkLatest: true
    - task: Bash@3
      displayName: 'Install Postman & Newman'
      inputs:
        targetType: 'inline'
        script: |
          #! /bin/bash
          pwd
          sudo snap install postman
          sudo npm install -g newman
          sudo npm install newman-reporter-junitfull -g
    - task: CmdLine@2
      displayName: Run Data Validation Tests
      inputs:
        script: 'newman run automatedtesting/postman/ValidationTest.postman_collection.json -e automatedtesting/postman/variable.postman_environment.json --reporters cli,junit --reporter-junit-export Results/TEST-DataValidation.xml'
        workingDirectory: '$(System.DefaultWorkingDirectory)'
      continueOnError: true
    - task: CmdLine@2
      displayName: Run Regression Tests
      inputs:
        script: 'newman run automatedtesting/postman/RegressionTest.postman_collection.json -e automatedtesting/postman/variable.postman_environment.json --reporters cli,junit --reporter-junit-export Results/TEST-Regression.xml'
        workingDirectory: '$(System.DefaultWorkingDirectory)'
      continueOnError: true
    - task: PublishTestResults@2
      displayName: Publish Test Reports
      condition: always()
      inputs:
        testResultsFormat: 'JUnit'
        testResultsFiles: '$(System.DefaultWorkingDirectory)/Results/*.xml'


# - stage: UITests
#   displayName: UI Tests - Selenium
#   jobs:
#   - deployment: VMRunUITests
#     displayName: Run UI Tests
#     environment:
#       name:  'VM-TEST'
#       resourceType: VirtualMachine
#     strategy:
#       runOnce:
#         deploy:
#           steps:
#           - download: current
#             displayName: 'Download Selenium'
#             artifact: selenium
#           - task: Bash@3
#             displayName: Selenium UI Tests
#             inputs:
#               targetType: 'inline'
#               script: |
#                 unzip -o $(Pipeline.Workspace)/selenium/selenium-tests.zip -d .
#                 sudo mkdir -p /var/log/selenium
#                 sudo chmod 664 /var/log/selenium
                
#                 sudo python3 -u python.py 2>&1 | sudo tee -a /var/log/selenium/selenium-test.log
#                 # copy selenium log file to $(System.DefaultWorkingDirectory)/log/selenium/
#                 cd $(System.DefaultWorkingDirectory)
#                 mkdir -p log/selenium
#                 pwd
#                 sudo cp /var/log/selenium/selenium-test.log log/selenium/selenium-test.log
#                 ls -la
#           - task: PublishPipelineArtifact@1
#             displayName: Publish selenium logs
#             inputs:
#               targetPath: '$(System.DefaultWorkingDirectory)/log/selenium/selenium-test.log'
#               artifactName: 'drop-selenium-logs'

- stage: DestroyIaC
  displayName: Destroy IaC
  jobs:
  - job: Destroy_Azure_IaC
    displayName: Destroy Azure IaC
    pool:
      name: MyAgentPool
    steps:
    - task: DownloadSecureFile@1
      name: tfvardef
      displayName: Download terraform.tfvars
      inputs:
        secureFile: 'terraform.tfvars'

    # Needed for Terraform VM deployment
    - task: InstallSSHKey@0
      displayName: Security Access
      inputs:
        #TODO 
        knownHostsEntry: 'ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ=='
        sshPublicKey: $(sshKey)
        sshKeySecureFile: 'id_rsa'
    - task: Bash@3
      displayName: Copy terraform.tfvars
      inputs:
        targetType: 'inline'
        script: cp $(Agent.TempDirectory)/terraform.tfvars $(System.DefaultWorkingDirectory)/terraform/environments/test
    - task: TerraformInstaller@0
      displayName: Install Terraform
      inputs:
        terraformVersion: '1.9.2'
    
    - task: TerraformCLI@1
      displayName: Terraform Init
      inputs:
        command: 'init'
        backendServiceArm: '$(backendServiceArm)'
        backendAzureRmResourceGroupName: 'tstate'
        backendAzureRmStorageAccountName: 'tstateanhdv29'
        backendAzureRmContainerName: 'tstate'
        backendAzureRmKey: 'terraform.tfstate'
        workingDirectory: '$(System.DefaultWorkingDirectory)/terraform/environments/test'
    
    - task: TerraformCLI@1
      displayName: Terraform Apply
      inputs:
        command: 'destroy'
        commandOptions: |
          -auto-approve
        workingDirectory: '$(System.DefaultWorkingDirectory)/terraform/environments/test'
